### ISSUE TITLE
Specifying a base path doesn't work

### ISSUE THREAD

**Issue by sazzer** [elmarti/camadb#65]
**Describe the bug**
Specifying the base path when creating a new Cama instance doesn't seem to work. Instead it's always using `./.cama` even though it shouldn't.

**Execute CamaDB with debug logging**
```
{
  level: 'info',
  message: 'Ensuring cama folder exists: /tmp/example/.cama'
}
{ level: 'debug', message: 'Initializing collection' }
{ level: 'debug', message: 'Initializing persistence adapter' }
{
  level: 'info',
  message: "Doesn't exist, creating: /tmp/example/.cama"
}
{
  level: 'info',
  message: 'Checking if folder exists for collectionmeta.json'
}
{ level: 'info', message: 'Does not exist, creatingmeta.json' }
```

**To Reproduce**
```
    database = new Cama({
        path: path.join(base, "database.cama"),
        persistenceAdapter: PersistenceAdapterEnum.FS,
        logLevel: LogLevel.Debug,
    });
```

**Expected behavior**
The data files will be stored in the directory provided to the Cama constructor.

**Comment by sazzer** [comment]
The problem seems to be that it's using the provided path as relative even though it shouldn't. I'm seeing this log:
```
(node:63945) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/tmp/example/tmp/database/database.cama/transactions/data'
```

When I'm running inside "/tmp/example" and I'm providing a path of "/tmp/database/database.cama". This should instead resolve to simply "/tmp/database/database.cama".

**Comment by elmarti** [comment]
Hey @sazzer thank you for raising a ticket - i've been off with flu all of the past week, so only just got round to looking into this. There's a big 'ol commit included above, i identified 2 problems: 
- The internal queueing system wasn't using a singleton library, so custom folder initialization wasn't working properly due to race conditions, centralizing the queueing system resolves this
- There was hardcoded logic for resolving the metadata folders, which varied slightly in 2 implementations. For this I have centralized the logic in a service. I'm going to do a bit more testing, but should be merging in the next day or so 

Thanks for raising on this new(ish) project! 🙌
